<?php

namespace AppBundle\Repository;

/**
 * KontynentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontynentRepository extends \Doctrine\ORM\EntityRepository
{
}
