<?php

namespace AppBundle\Repository;

/**
 * PanstwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanstwoRepository extends \Doctrine\ORM\EntityRepository
{
}
