# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    Card:
        class: AppBundle\Services\Card
        arguments: []
    Deck:
        class: AppBundle\Services\Deck
        arguments: ['../src/AppBundle/Resources/Config/cards.yml']
