# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    Card:
        class: AppBundle\Services\Card
        arguments: []
    DeckGenerator:
        class: AppBundle\Services\DeckGenerator
        arguments: ['../src/AppBundle/Resources/Config/cards.yml']
        calls:
            - method: shuffleDeck
    HandsGenerator:
        class: AppBundle\Services\HandsGenerator
        arguments: ['@DeckGenerator']
        calls:
            - method: distributeCards
    Table:
        class: AppBundle\Services\Table
        arguments: []
